app = "riverbenk-api"
primary_region = "lhr"

[build]
  dockerfile = "./Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.concurrency]]
  type = "requests"
  soft_limit = 500
  hard_limit = 100
